### PR TITLE
Fix main.py and monitor.py

### PR DESCRIPTION
**Pull request by LittleToonCat**
Those two files were broken after the doubles branch merge, so I've taking the liberty of fixing them by using new arguments, values and other stuff.

P.S.  Do we even need the `crashchecker.py` file anymore, seeing that all crash detection are seemingly handled by the engine itself?

### CODE REVIEW

**Comment by ferraro1** [comment]
Oh, awesome! When things aren't on fire I also need to add more documentation and maybe a few flowcharts describing the various complex things pbrEngine does and why they are guaranteed to work correctly given certain assumptions that always seem to be holding, at least for animations speeds <=2.

I also have some ideas on memory reads that could potentially make the move and switch selection algorithms a lot simpler than what they have been, which would render the extra doc & flowchart stuff unnecessary. I wasn't sure if I'd get around to doing this because even though it'd make the existing logic simpler, the existing logic works, and in the end it's significant work for something that might end up breaking in rare cases and only achieves simpler logic.

But to answer your question, only some crash detection is handled by the engine now, and I moved it in out of necessity.  The `no frame advanced` detection in `crashchecker.py` is a duplicate of the same detecetion in the core's `pbr.py:_crashchecker`, and I *think* that could probably be moved into the engine as well, so the upper layer doesn't have to duplicate that functionality.  It's another thing I didn't get to mostly because it was already in a working state.

**Comment by Felk** [comment]
My thoughts behind the structuring was this:
- Everything in the pbrEngine *sub*directory is part of the engine
- Stuff in the root directory are examples, utilities for standalone-mode or various other stuff
- Files like `main.py` and `monitor.py` aren't needed by the core, but crashchecking is. The core therefore copies the example so to speak.

I initially thought that crash detection will be vastly different between the standalone mode and integrated into the core. Since they are quite similar and one could argue that the engine knows best how to detect crashes, that could indeed be put into the engine itself

**Comment by ferraro1** [comment]
Sounds good.  I was wondering whether it matters that you were were thinking to run pbrEngine inside of dolphin at some point.  Would pbrEngine then be another python process entirely? Which would communicate to the core's python process via a socket or something?

And if so, what would happen to pbrEngine if dolphin crashed?  Would we want to keep some crash detection external to pbrEngine in that case?

Or do I have this all backwards?

**Comment by Felk** [comment]
I have not figured out how it would run inside of dolphin yet

**Pull request merged**
